### ISSUE TITLE
Missing SubmissionFile constants

### ISSUE THREAD

**Issue by Rhynden** [Vitaliy-1/JATSParserPlugin#66]
Hi,
I think the JatsParserPlugin.inc.php is missing the import 
`import('lib.pkp.classes.submission.SubmissionFile');`

My version in use: OJS and Plugin both with  Stable-3_3_0

At least when I added the import my errors went away, but maybe it was a setup error on my side.

`PHP Fatal error:  Uncaught Error: Undefined constant "SUBMISS
ION_FILE_PRODUCTION_READY" in C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsPar
ser\JatsParserPlugin.inc.php:343
Stack trace:
#0 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\plugins\HookRegistry.inc.php(107):
 JatsParserPlugin->publicationTemplateData('Template::Workf...', Array)
#1 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\template\PKPTemplateManager.inc.ph
p(1518): HookRegistry::call('Template::Workf...', Array)
#2 C:\Users\flori\Documents\ojs-3_3_0\cache\t_compile\ee131ee78aae66ec621d8f4e466e22416b
f8d89c^5b2b400be3d78bc0ae391c12ce66fa93bd43d118_0.app.workflowworkflow.tpl.php(300): PKP
TemplateManager->smartyCallHook(Array, Object(Smarty_Internal_Template))
#3 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\s
marty_internal_runtime_inheritance.php(248): Block_89746662961b9b9d9711de2_16075353->cal
lBlock(Object(Smarty_Internal_Template))
#4 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\s
marty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBl
ock(Object(Block_89746662961b9b9d9711de2_16075353), Object(Smarty_Internal_Template))
#5 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\s
marty_internal_runtime_inheritance.php(186): Smarty_Internal_Runtime_Inheritance->proces
s(Object(Smarty_Internal_Template), Object(Block_89746662961b9b9d9711de2_16075353), Obje
ct(Block_74944453761b9b9d9893d86_43569915))
#6 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\s
marty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->proces
s(Object(Smarty_Internal_Template), Object(Block_74944453761b9b9d9893d86_43569915))
#7 C:\Users\flori\Documents\ojs-3_3_0\cache\t_compile\ee131ee78aae66ec621d8f4e466e22416b
f8d89c^164bd5a4f3891532cf93e9d19911fe9cb3308efd_0.app.layoutsbackend.tpl.php(234): Smart
y_Internal_Runtime_Inheritance->instanceBlock(Object(Smarty_Internal_Template), 'Block_7
49444537...', 'page')
#8 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\s
marty_template_resource_base.php(123): content_61b9b9d9898797_38744010(Object(Smarty_Int
ernal_Template))
#9 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\s
marty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode
(Object(Smarty_Internal_Template))
#10 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Intern
al_Template))
#11 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_internal_template.php(385): Smarty_Internal_Template->render()
#12 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRend
er('layouts/backend...', NULL, 'ee131ee78aae66e...', 0, 3600, Array, 2, false, NULL, NUL
L)
#13 C:\Users\flori\Documents\ojs-3_3_0\cache\t_compile\ee131ee78aae66ec621d8f4e466e22416
bf8d89c^5b2b400be3d78bc0ae391c12ce66fa93bd43d118_0.app.workflowworkflow.tpl.php(34): Sma
rty_Internal_Runtime_Inheritance->endChild(Object(Smarty_Internal_Template), 'layouts/ba
ckend...')
#14 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_template_resource_base.php(123): content_61b9b9d97290d0_63589594(Object(Smarty_In
ternal_Template))
#15 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCod
e(Object(Smarty_Internal_Template))
#16 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Intern
al_Template))
#17 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#18 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\
smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Sma
rty_Internal_Template), NULL, 'ee131ee78aae66e...', NULL, 1)
#19 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\template\PKPTemplateManager.inc.p
hp(1187): Smarty_Internal_TemplateBase->display('workflow/workfl...', NULL, 'ee131ee78aa
e66e...', NULL)
#20 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\pages\workflow\PKPWorkflowHandler.inc.php
(415): PKPTemplateManager->display('workflow/workfl...')
#21 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPRouter.inc.php(395): PKPW
orkflowHandler->index(Array, Object(Request))
#22 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPPageRouter.inc.php(246):
PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#23 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\Dispatcher.inc.php(144): PKP
PageRouter->route(Object(Request))
#24 C:\Users\flori\Documents\ojs-3_3_0\lib\pkp\classes\core\PKPApplication.inc.php(362):
 Dispatcher->dispatch(Object(Request))
#25 C:\Users\flori\Documents\ojs-3_3_0\index.php(68): PKPApplication->execute()
#26 {main}
  thrown in C:\Users\flori\Documents\ojs-3_3_0\plugins\generic\jatsParser\JatsParserPlug
in.inc.php on line 343`

Cheers 
Rhynden

**Comment by Vitaliy-1** [comment]
Hi @Rhynden,

are you still encountering the error with a stable-3_3_0 branch? If yes, can you check when this error occurs?
I'm testing it on OJS 3.3.0-8 where I'm unable to reproduce it. Is it the case when upgrading OJS?

**Comment by Rhynden** [comment]
Hello @Vitaliy-1 ,
sorry for not responding back, quite busy at the moment.
We currently got a somehow working setup for us, therefore we aren't experimenting with anything else.
Also I would not really know how to help you with that, since I'm not really familiar with OJS anyways., maybe it was just an error on my side.
Sorry about that :/
Anyways, we would like to give you some compensation for your help and very useful repositories!
Is there any way we can pay you? 
Kind regards
